# Generated by Django 3.0.3 on 2020-04-27 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0003_remove_gallery_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
