# Generated by Django 3.0.3 on 2020-04-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0004_delete_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='image', max_length=25)),
                ('gal_img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
