# Generated by Django 3.0.3 on 2020-04-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0005_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gal_img',
            field=models.ImageField(upload_to='mainweb/images'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='mainweb/image', max_length=25),
        ),
    ]
