# Generated by Django 3.0.3 on 2020-04-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0006_auto_20200427_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('position', models.CharField(max_length=25)),
                ('desc', models.CharField(max_length=25)),
                ('img', models.ImageField(upload_to='mainweb/images')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonianls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('desc', models.CharField(max_length=25)),
                ('company', models.CharField(max_length=25)),
                ('img', models.ImageField(upload_to='mainweb/images')),
            ],
        ),
    ]
