# Generated by Django 3.0.3 on 2020-04-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0007_team_testimonianls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='testimonianls',
            name='desc',
            field=models.CharField(max_length=2000),
        ),
    ]
