# Generated by Django 3.0.3 on 2020-04-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0008_auto_20200427_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='desc',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.CharField(max_length=20),
        ),
    ]
